### ISSUE TITLE
Linq 'Contains' SerializationException

### ISSUE THREAD

**Issue by nsouca** [esskar/Serialize.Linq#103]
I'm using the library for various expressions and it works great. However, when I add a condition using the keyword 'Contains', I get a SerializationException message.

**Comment by nsouca** [comment]
More details:

1. Expression which I'm trying to serialize
Expression<Func<Folder, bool>> inboxTabExpression = (folder) => folder.PostIts.Any(postit => inboxIds.Contains(postit.CurrentAssignee.AssigneeId));
where inboxIds is a list of int.

2. Exception details
Error converting type: Type 'System.Collections.Generic.List`1[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]' with data contract name 'ArrayOfint:http://schemas.microsoft.com/2003/10/Serialization/Arrays' is not expected. Consider using a DataContractResolver if you are using DataContractSerializer or add any types not known statically to the list of known types - for example, by using the KnownTypeAttribute attribute or by adding them to the list of known types passed to the serializer.

3. StackTrace
   at Serialize.Linq.Serializers.TextSerializer.Serialize[T](T obj)
   at Serialize.Linq.Serializers.ExpressionSerializer.SerializeText(Expression expression, FactorySettings factorySettings)

**Comment by esskar** [comment]
Try setting `AutoAddKnownTypesAsListTypes = true`. See Issue #96

**Comment by nsouca** [comment]
AutoAddKnownTypesAsListTypes did the trick. Thanks! :)
