### ISSUE TITLE
BlockExpression not supported?

### ISSUE THREAD

**Issue by KevinSWork** [esskar/Serialize.Linq#104]
I see that BlockExpression is not supported as a node type.  Is that because there are technical issues that prevent that type from being serialized, or is that just a matter of not being needed for the use cases that you've supported so far?

**Comment by esskar** [comment]
hi. it is not needed. do you have a use case? any example that is not working?

**Comment by KevinSWork** [comment]
`
        static void Main(string[] args)
        {
            Expression<Func<int, string>> expression = num => num.ToString();

            var parameter = Expression.Parameter(typeof(int), "num");

            BlockExpression block = Expression.Block(
                Expression.Invoke(expression, parameter));

            Expression<Func<int, string>> combinedExpression =
                Expression.Lambda<Func<int, string>>(
                    block,
                    parameter);

            // This line throws an exception: System.ArgumentException: 'Unknown expression of type System.Linq.Expressions.BlockN'
            string serialized = combinedExpression.ToJson();

            var func = combinedExpression.Compile();

            Console.WriteLine(func(42));
        }
`
I wrote the above code as a 4.6.1 Framework console app in C# using v1.7.1 of the Serialize.Linq nuget package.

Given this error and a quick look through your code (nice code, by the way), it looked like block expressions simply weren't supported (there's no BlockExpressionNode under the Nodes folder).

I was able to create one locally, but I too new to expression trees to know whether there was a technical reason why such a thing would be a bad idea (and, thus, the omission was intentional) or if you just didn't have a use case that needed it.

I don't currently require this feature.  At the moment, I'm poking around to determine what is and is not possible with expression trees in general (I have a WCF service that could potentially benefit from being able to serialize expression trees).  So, I'm really just curious at this point.

Thanks!

**Comment by esskar** [comment]
Well, by the time i wrote the library, i didn't know how to create a block expression from lambda expression, like x => ... so i was not able to test it, so i skipped it.
If you want, i can look into it.

**Comment by KevinSWork** [comment]
Thanks for the response.  No need to look into it on my behalf.  You've answered my curiosity -- you're not aware of anything that would prevent the BlockExpression from being supported.  If I decide to move forward with using Serialize.Linq and find that I really need that support, I'll reach out again (potentially via a pull request).

Thanks so much for your time.
