### ISSUE TITLE
Help need to use binary serializater

### ISSUE THREAD

**Issue by manuprendlair** [esskar/Serialize.Linq#116]
Hello,

I would like to serialize an expression with your library:
I found an example with the jsonserializater but not with BinarySerializer.
I try to change this example :

```
            Expression expression = Expression.Parameter(typeof(Person), "x");

            // Serialize expression
            var serializer = new ExpressionSerializer(new JsonSerializer());
            string value = serializer.SerializeText(expression);
            Console.WriteLine("value:" + value);
```
with
` var serializer = new ExpressionSerializer(new BinarySerializer());`

but this not working like that...

Could you give a very simple example to use the BinarySerializer ?

Thanks,
Emmanel, France.

**Comment by manuprendlair** [comment]
Answer to myself, if it could help somebody : 

```
            ISerializer binSerializer = new BinarySerializer();
            var serializer = new ExpressionSerializer(binSerializer);
            var serialized_expression = serializer.SerializeBinary(my_expression);
```

**Comment by esskar** [comment]
Exactly, you cant serialize expressions as text with a binary serializer.
