### ISSUE TITLE
Support for Anonymous Types

### ISSUE THREAD

**Issue by JasonKStevens** [esskar/Serialize.Linq#117]
Problem
I'm using your library to write an IQbservable for EventStore and it would make all the difference if it could support anonymous types.  Currently, when I create an anonymous type like say, `.Select(e => new { data = e.Data })`, I get the following error: `System.Exception: Unsupported linq expression: Failed to serialize '<>f__AnonymousType0'1`
EDIT: I need to do more testing because it seems the client serialization happens fine... it might be something on the server side which lead me to jump to conclusion.  I'll come back in a few days when I get a chance to drill into it.

Solution
Newtonsoft has a JsonConvert.DeserializeAnonymousType() method but it needs an instance of the anonymous type.  I figure this could be used at some place in your library but haven't looked through the code.

Alternatives
An alternative might be for me to look at implementing this feature myself?  Pointers would be awesome.

**Comment by esskar** [comment]
The library does not use Newtonsoft.Json, but the .net framework json serializer.
if can up with a pull request, i am more than happy to merge it.
Not sure if i will have time in the near future to look at it.

**Comment by JasonKStevens** [comment]
Okay great I'll look into it, thanks for the response.

**Comment by esskar** [comment]
Closed due to inactivity. @JasonKStevens  if you still need help, feel free to reopen/comment.
