### ISSUE TITLE
Minimal serialization for lambda expressions

### ISSUE THREAD

**Issue by jgauffin** [esskar/Serialize.Linq#118]
Is it possible to deserialize the output from ExpressionNode.ToString() to create an expression again for simple lambda expressions?

I got the following flow:

1. The library user defines a filter for a type: `AddFilter<MyEntity>(x=>x. Age < 10);`
2. The lambda expression is sent to a backend using `filter.ToExpressionNode.ToString()` 
3. In the backend I want to deserialize the expression again.
4. As the backend do not the have the right assembly loaded I use an `ExpressionVisitor` to modify the expression so that it uses a `Dictionary<string,string>` and `Convert.ChangeType`.

I got everything working, including modifying the expression in 4, but the deserialization.

**Comment by esskar** [comment]
Can you add a minimal example?

**Comment by esskar** [comment]
Closed due to inactivity. @jgauffin if you still need help, try adding more information to what you want/expect. thanks
