### ISSUE TITLE
Support for IndexExpression

### ISSUE THREAD

**Issue by jgauffin** [esskar/Serialize.Linq#119]
**Is your feature request related to a problem? Please describe.**

I have an expression that uses a dictionary. But I can't serialize it as Serialize.Linq do not support [IndexExpression](https://docs.microsoft.com/en-us/dotnet/api/system.linq.expressions.indexexpression?view=netframework-4.8).

**Describe the solution you'd like**

Suport for `IndexExpression` so that something like:

`Expression<Func<Dictionary<string,string>, bool>> filterExpression = filter => (int)Convert.ChangeType(filter["Age"], typeof(int)) < 10;`

can be serialized.

**Background**

I'm building a messaging system where developers may filter messages using LINQ expressions.

A dev might use something like: `subscription.Filter<MyDTO>(x => x.Age < 10)`.

But since the messaging system doesn't have access to the assembly that the `MyDTO` type is located in I'm transforming the expression to use a `Dictionary<string,string>` instead before transferring the expression to the messaging system.

That's why I have wierd looking expressions :)

**Comment by esskar** [comment]
@jgauffin See my commit and the new unit test that comes with it. Your example works. Can you provide a test that is not working for you?

**Comment by jgauffin** [comment]
Thank you for the quick reply.

Here is a modified test: 
https://gist.github.com/jgauffin/090bef80b59d3b20cca6a3758705b62e

It's when I use my visitor that it fails.

**Comment by esskar** [comment]
this will not work; even if i add support for IndexExpression, CultureInfo will not be serializable

https://gist.github.com/jgauffin/090bef80b59d3b20cca6a3758705b62e#file-issue119-cs-L121

**Comment by jgauffin** [comment]
I can get rid of the culture. I've been playing around a lot to try to get everything work, so the code might contain things that are not required.

**Comment by esskar** [comment]
ok, i think i made it work (without CultureInfo).
Can you check it before i release it to nuget?

**Comment by esskar** [comment]
@jgauffin any chance to test it or do you need a prerelease as nuget?

**Comment by jgauffin** [comment]
yes, I will check tomorrow. thanks!

**Comment by jgauffin** [comment]
It works fine. Thank you for the help!
