### ISSUE TITLE
Problem with deserializing DateTime property

### ISSUE THREAD

**Issue by Mansu12135** [esskar/Serialize.Linq#121]
Hi,

We use your library for serializing and deserializing our queries. It works like a scharm, thank you. But our service are located in different time zone from our clients. From this reason when we deserialize their query datetime fields has incorrect value. We think it's problem in different time zone. Can you help us resolve this issue. 

Thank you.

**Comment by esskar** [comment]
Hi @Mansu12135 , thanks for using the library.
Well, you should always use UTC for datetime values, or even better, use [DateTimeOffset](https://docs.microsoft.com/en-us/dotnet/api/system.datetimeoffset?view=netframework-4.8) instead of `DateTime`

**Comment by Mansu12135** [comment]
Hi @esskar , I understand you. When we need to store date format we use DateTimeOffset. But in our case, user set date range for report, we need to transfer DateTime. But it does not work correctly on server side.

**Comment by esskar** [comment]
But still, i think your users need to send timestamps as UTC... but anyways, i think it has nothing to do with any problem of the library.

**Comment by Mansu12135** [comment]
You are right, we changed all DateTime variable to UTC kind. After that all works correct. Thank you.
