### ISSUE TITLE
Problem with deserialization of ICollection<T> typed

### ISSUE THREAD

**Issue by GoNextGroup** [esskar/Serialize.Linq#124]
Each time I try to serialize/deserialize Expression like this:

`e => request.Ids.Contains(e.Id) & e.UserId == request.Id`

where `Ids` is a `ICollection<Guid>` and `Id`, `UserId` are Guids, I get an error on deserialization:

`Constructor on type 'System.Collections.Generic.ICollection`1[[System.Guid, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]' not found.
`

If I change `ICollection<Guid>` on `List<Guid>`, I have well-working code. 
In the serializer settings I set parameters for well-known types like this:

```
            expressionJsonSerializer.AddKnownType(typeof(Guid));
            expressionJsonSerializer.AddKnownType(typeof(Enum));
            //expressionJsonSerializer.AutoAddKnownTypesAsArrayTypes = true;
            expressionJsonSerializer.AutoAddKnownTypesAsListTypes = true;
```

Is it possible to fix this problem in your library? 

Thnx a lot!

**Comment by esskar** [comment]
What serializer are you using? see commit that it can work; b9f78777c28789878f172db1c23e01024a76e849

Please show code to reproduce your finding
