### ISSUE TITLE
Support for asp.net core 3.1

### ISSUE THREAD

**Issue by pvanroos** [esskar/Serialize.Linq#125]
Do you plan on supporting 3.1?

**Comment by GoNextGroup** [comment]
I have it works well in all of my ASP.NET Core 3.1 projects. What problems do you have?

**Comment by pvanroos** [comment]
You're right.  It works great in my project too.  Sorry I opened this and wasted your time.

**Comment by GoNextGroup** [comment]
Nevermind. I hope, the author of this project will come back and continue developing it - there are some problems still here (for example, with interfaces).

**Comment by pvanroos** [comment]
I agree.  I'm interested in how you are using it.  I have built a couple of Blazor web apps that connect to an AspNet Core 3.1 web api service.  It's great to be able to pass the Linq queries from these apps down through the stack.  The persistence store I use is a CosmosDb instance where I use the GetItemLinqQueryable construct to pass the expression body to and get only what was requested.  Then I return the data as an IAsyncEnumerable--yielding items immediately as they flow across the wire.  Obviously if I had non-.NET clients, I would utilize a different type of service interface--perhaps a GraphQL service--I don't know.  Come to think of it, a GraphQL translation to expressions would be cool there.  My overall goal to provide granular control over what the endpoint returns and efficiently flow the data to the client.
