### ISSUE TITLE
MongoDb.Bson.ObjectId problem

### ISSUE THREAD

**Issue by mRmEEeZ** [esskar/Serialize.Linq#126]
**Describe the bug**
default JsonSerializer can't serialize ObjectId struct type when a => a.Id

**To Reproduce**
```
public DeleteRequest(Expression<Func<TDocument, bool>> expression = null)
        {
            serializer = new ExpressionSerializer(new Serialize.Linq.Serializers.JsonSerializer());
            Expression<Func<TDocument, bool>> _defaultExpression = a => false;
            SerializedPredicate = serializer.SerializeText(expression ?? _defaultExpression);
====> expression = a => a.Id == someObjectIdValue
        }
```
and it shows this error:

> Error converting type: Type 'MongoDB.Bson.ObjectId' with data contract name 'ObjectId:http://schemas.datacontract.org/2004/07/MongoDB.Bson' is not expected. Add any types not known statically to the list of known types - for example, by using the KnownTypeAttribute attribute or by adding them to the list of known types passed to DataContractSerializer.

**Expected behavior**
should be serialized normally.

**Desktop (please complete the following information):**
 - Windows 10 , VS 2019

**Comment by esskar** [comment]
Hi,

it's not a bug, just try adding the missing types as known types

```serializer.AddKnownType(typeof(MongoDB.Bson.ObjectId));```
