### ISSUE TITLE
Question on LambdaExpression serialization

### ISSUE THREAD

**Issue by kitog** [esskar/Serialize.Linq#128]
I'm trying to understand why the following examples behaves as it does:

    var nowProp = typeof(DateTime).GetProperty(nameof(DateTime.Now));
	var trueClause = Expression.Call(Expression.MakeMemberAccess(null, nowProp), "ToString", Type.EmptyTypes);
 
	var falseClause = Expression.Constant("N/A", typeof(string));
	var condition = Expression.Constant(true);
	var conditional = Expression.Condition(condition, trueClause, falseClause);

	var lambda = Expression.Lambda<Func<string>>(conditional);
	var initial = lambda.Compile()();

	var serializer = new ExpressionSerializer(new JsonSerializer());
	var serializedLambda = serializer.SerializeText(lambda);
	
	Thread.Sleep(2000);
	
	var deserializedExpression = serializer.DeserializeText(serializedLambda) as Expression<Func<string>>;
	var readBackFn = deserializedExpression.Compile();
	var readBack = readBackFn().ToString();
	
	// Expected to see 2 seconds between initial and readBack, but they are the same as the serialized lambda contains the actual date
	// and not the DateTime.Now property.
	Console.WriteLine($"initial:{initial}, read-back:{readBack}");

**Comment by esskar** [comment]
Have a look at the serialized text (`Console.WriteLine(serializedLambda)'):

```
{"__type":"LambdaExpressionNode:#Serialize.Linq.Nodes","NodeType":18,"Type":{"GenericArguments":[{"Name":"System.String"}],"Name":"System.Func`1"},"Body":{"__type":"ConditionalExpressionNode:#Serialize.Linq.Nodes","NodeType":8,"Type":{"Name":"System.String"},"IfFalse":{"__type":"ConstantExpressionNode:#Serialize.Linq.Nodes","NodeType":9,"Type":{"Name":"System.String"},"Value":"N\/A"},"IfTrue":{"__type":"ConstantExpressionNode:#Serialize.Linq.Nodes","NodeType":9,"Type":{"Name":"System.String"},"Value":"10.12.2020 23:26:15"},"Test":{"__type":"ConstantExpressionNode:#Serialize.Linq.Nodes","NodeType":9,"Type":{"Name":"System.Boolean"},"Value":true}},"Parameters":[]}
```

you want something like that (it is not the same, but the this way, the Now is not called during the expression build.

```
Expression<Func<string>> expression = () => true ? DateTime.Now.ToString() : "N/A";
var initial = expression.Compile()();

var serializer = new ExpressionSerializer(new JsonSerializer());
var serializedLambda = serializer.SerializeText(expression);

Thread.Sleep(2000);

var deserializedExpression = (Expression<Func<string>>) serializer.DeserializeText(serializedLambda);
var readBackFn = deserializedExpression.Compile();
var readBack = readBackFn();

Console.WriteLine($"initial:{initial}, read-back:{readBack}");
```
