### ISSUE TITLE
Cannot Serialize Expression Converted From Func

### ISSUE THREAD

**Issue by kyleherzog** [esskar/Serialize.Linq#137]
**Describe the bug**
If I have a `Func<object, object>` and convert it to an `Expression<Func<object, object>>` it will throw a `SerializationException` when calling `ExpressionSerializer.SerializeText()`.  

**To Reproduce**
```C#
Func<object, object> f = x => x;
Expression<Func<object, object>> exp = x => f(x);
var expressionSerializer = new ExpressionSerializer(new Serialize.Linq.Serializers.JsonSerializer());
var serialized = expressionSerializer.SerializeText(exp);
```

https://dotnetfiddle.net/mD1G6Y

**Expected behavior**
To serialize the expression.

**Comment by esskar** [comment]
I have some time over the holidays; will have a look. Thanks for the issue and using the library.

**Comment by esskar** [comment]
Even tough `Func<object, object>` statements look like expressions, they are not expressions. So they cannot be serialised. 
The workaround shown by @oahrens is also not a equivalent to the problem because it is only using a call expression that may or may not be the same after deserialisation.
