### ISSUE TITLE
Change of License

### ISSUE THREAD

**Issue by esskar** [esskar/Serialize.Linq#142]
Hello Contributors,

I want to change to license of the library to MIT. To be able to do this, I need the permission of the contributors.
Can you please answer with YES, if you agree to licence change, and NO (maybe with a reason), if you not agree with the change.
Thank you very much,

@StefH @OlegNadymov @vcaraulean @artemnf @vsoldatkin @gldfdp @jogibear9988

**Comment by StefH** [comment]
YES

**Comment by jogibear9988** [comment]
yes

**Comment by gldfdp** [comment]
Yes

Télécharger Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by vsoldatkin** [comment]
Yes

**Comment by OlegNadymov** [comment]
Yes

**Comment by vcaraulean** [comment]
Yes
