### ISSUE TITLE
Expression.Default not supported in serialization

### ISSUE THREAD

**Issue by cjvanwyk3** [esskar/Serialize.Linq#146]
Hello,

I have some expressions that use Expression.Default and they are not serializing.  Here is a simplistic example to re-create the issue:

        var defaultValue = Expression.Default(typeof(int));
        var expressionSerializer = new Serialize.Linq.Serializers.ExpressionSerializer(new Serialize.Linq.Serializers.JsonSerializer());
        var serialized = expressionSerializer.SerializeText(defaultValue);

Here is the error i get.
System.ArgumentException: Unknown expression of type System.Linq.Expressions.DefaultExpression

  Stack Trace: 
NodeFactory.Create(Expression expression)
    ExpressionConverter.Convert(Expression expression, FactorySettings factorySettings)
    ExpressionSerializer.SerializeText(Expression expression, FactorySettings factorySettings)

Thanks,
Curt

**Comment by esskar** [comment]
It think its fixed. Will provide a new nuget package later.
thanks for the issue report

**Comment by esskar** [comment]
Version 3 has been published
