### ISSUE TITLE
Need your help with other issue

### ISSUE THREAD

**Issue by GarciaKompact** [esskar/Serialize.Linq#155]
Hi @esskar sorry to contact you by this way, but could not find any other way... If you can't help me or if you find this anoying, feel free to delete this post, I understand.

So, to summarise I need to build and app that will work with the Intermec PB51 printer and I can't find any ESC /P reference manual from Intermec, then I found your post: 
https://stackoverflow.com/questions/33646515/intermec-pb51-says-it-has-864-dots-across-but-it-has-only-832
In the post you are trying to do exactly what I need to do, but I can't find any manual with the commands that you talk about.

With this I candly ask you if you still have it, to send me some how the manual that you used to communicate with the PB51 printer.

Best Regards,
Gonçalo Garcia.

**Comment by GarciaKompact** [comment]
.

**Comment by esskar** [comment]
Hi, no worries. But i can't help you here. I did the implementation way back for a customer, and i have no longer the documentation.
