### ISSUE TITLE
Undefined variable error when using ToString in lambda expression

### ISSUE THREAD

**Issue by xeo545x39** [esskar/Serialize.Linq#159]
1. Use serializer with default settings
2. Instantiate following expressions
3. Use `SerializeText` method

This **works**.

`context => context.GetType().Name + '1'`

Expression type: ```System.Linq.Expressions.Expression1`1[System.Func`2[Namespace.Context,System.String]]```

Body:` (context.GetType().Name + Convert(1, Object))`

IL:

```
.Lambda #Lambda1<System.Func`2[Namespace.Context,System.String]>(Namespace.Context $context)
{
    (.Call $context.GetType()).Name + (System.Object)'1'
}
```
-----------
This does **not** work.

`context => context.Previous.Output["rate"].ToString()`

Expression type: ```System.Linq.Expressions.Expression1`1[System.Func`2[Namespace.Context,System.String]]```

Body: `context.Previous.Output.get_Item("rate").ToString()`

IL:

```
.Lambda #Lambda1<System.Func`2[Namespace.Context,System.String]>(Namespace.Context $context)
{
    .Call (.Call (($context.Previous).Output).get_Item("rate")).ToString()
}
```
The error is: variable 'context' of type 'Namespace.Context' referenced from scope '', but it is not defined

Expression parameters seems the same in both cases. I've tried also this:

`context => (string)context.Previous.Output["rate"] + '1'`

So change `ToString` to `string` casting - it **works**

**Comment by esskar** [comment]
Can you provide a reproducible example?

**Comment by xeo545x39** [comment]
I've resolved this by passing **same** parameter **instance** instead of just "same" parameter, so key was the same.
