### ISSUE TITLE
Deploy the latest build to NuGet

### ISSUE THREAD

**Issue by michsco** [esskar/Serialize.Linq#160]
* NuGet.org shows the last publish of this package was in 2020, but there have been commits since then. Can the latest version of the package be published?
* Can the library be updated to support .NET 7.0 as well?

**Comment by sommmen** [comment]
@esskar Hello - could you deploy the latest master code to nuget?

**Comment by esskar** [comment]
sorry. will do this asap

**Comment by esskar** [comment]
Version 3 has been published
