### ISSUE TITLE
Serialize Linq Expression not working - Workaround / Suggestion

### ISSUE THREAD

**Issue by jacodv** [esskar/Serialize.Linq#161]
**Describe the bug**
I am trying to serialize a simple expression that must be executed on another server.  I have tried various solutions.  No success.  The string representation of the expression is: 
* `System.Collections.Generic.List`1[Person].Where(x => (x.Age > 35)).Where(x => x.Name.Contains("Peter"))`
* I need to deserialize the `Where` on the backend.  The expression will be sent as a message to a queue for later processing

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to '[Scratch pad] to simulate (https://dotnetfiddle.net/5fhVS5)'
2. OR See the code below

**Code**
```{csharp}
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using Serialize.Linq;
using Serialize.Linq.Factories;

					
public class Program
{
	public static void Main()
	{
		var people = new List<Person>();
		var peopleQuery = people.AsQueryable();
		
		peopleQuery = peopleQuery.Where(x=>x.Age>35);
		peopleQuery = peopleQuery.Where(x=>x.Name.Contains("Peter"));
		var expression = peopleQuery.Expression;
		
		var serializer = new Serialize.Linq.Serializers.ExpressionSerializer(new Serialize.Linq.Serializers.JsonSerializer())
		{
		  AutoAddKnownTypesAsArrayTypes = false,
		  AutoAddKnownTypesAsListTypes = false
		};
	    var serialized = serializer.SerializeText(expression, new FactorySettings() { AllowPrivateFieldAccess = true, UseRelaxedTypeNames = true });

		Console.WriteLine(serialized);
	}
}

public class Person{
public string Name {get;set;}
public int Age{get;set;}
}
```

**Expected behaviour**
JSON/XML string representing the linq expression.

**Additional context**
.Net 6

**Comment by esskar** [comment]
Hi, the workaround would be to write the expression as

`Expression<Func<Person, bool>> expression = x => x.Age > 35 && x.Name.Contains("Peter");`

Does this help?

**Comment by jacodv** [comment]
No is does not, thanks.  I cannot control the expression syntax received from the input
