### ISSUE TITLE
Target framework net standard 2.0 & 2.1

### ISSUE THREAD

**Issue by olabacker** [esskar/Serialize.Linq#166]
Hey!

I am using this in a project where i am using netstanard 2.0 mostly and I get warnings since it only supports net 4.8 & 5+. 

Is there a specific reason for this? If not, I could add a pr adding those two tfms.

**Comment by esskar** [comment]
No special reason; feel free to submit PR

**Comment by esskar** [comment]
Merged. Sorry it took me so long.

**Comment by olabacker** [comment]
No worries! thanks
