### ISSUE TITLE
Does not work with related objects

### ISSUE THREAD

**Issue by syedhasanraza** [esskar/Serialize.Linq#38]
Hi,
My objective is to serialize Expression Trees. The library works as a charm when we write expressions on an object, but when we add expression for a related IQueryable() object, we get "Expression not allowed" exception.

for e.g. We have following classes

        public class Order
        {
            public virtual int Id { get; set; }
            public virtual int qty { get; set; }
        }
        public class Document
        {
            public virtual int Id { get; set; }
            public virtual ICollection<Order> Orders { get; set; }
        }

          //i want to query Document object based on related object Order with below expression
            Expression<Func<Order, bool>> predicate = x => x.Id > 0 && x.Id < 5;

            Expression<Func<Document, bool>> pred = x => x.Orders.AsQueryable().Any(predicate);

            var serializer = new ExpressionSerializer(new BinarySerializer());
            var value = serializer.SerializeBinary(pred);

The last line above resulted in error "Expression not allowed"

Thanks
Syed

**Comment by esskar** [comment]
IQueryAble is not supported. Why do you think, you need to convert it to IQueryable here?

**Comment by syedhasanraza** [comment]
Actually I want to serialize expression having queries on related objects. The expression " x => x.Id > 0 && x.Id < 5" is provided just for example, however in actual project I am using generic class to build Dynamic expression, passing only filter values etc.

So, in order to query on related ICollection object, i have to convert it to AsQueryable() before passing the filter predicate, containing dynamic filter expression.
i.e.
Expression<Func<Document, bool>> pred = x => x.Orders.AsQueryable().Any(predicate);

**Comment by esskar** [comment]
i commited something. can you please use the current github version to run your tests?

**Comment by syedhasanraza** [comment]
I tested, and it worked perfectly fine :+1:

**Comment by syedhasanraza** [comment]
Are you going to release a new version on nuget?

**Comment by esskar** [comment]
yes, i will try to do it until the end of the week!

**Comment by syedhasanraza** [comment]
Still waiting for new version on nuget?

**Comment by esskar** [comment]
pushed!
