### ISSUE TITLE
Serialization over NServiceBus; System.MemberAccessException: Cannot create an abstract class.

### ISSUE THREAD

**Issue by Odeanathus** [esskar/Serialize.Linq#45]
This might ben more of an issue in NServiceBus than in Serialize.Linq, not entirely sure but I'll post it here regardless.

When attempting to make a call over NServiceBus where we've created a Message with in it a Property of the type ExpressionNode the message seems to get serialized perfectly fine. However on the service end when Deserializing we get the following exception;

ERROR NServiceBus.Unicast.Transport.TransportReceiver Failed to deserialize message with ID: c6e85a3a-ed9f-4211-809f-a44500d99727
NServiceBus.MessageDeserializationException: An error occurred while attempting to extract logical messages from transport message c6e85a3a-ed9f-4211-809f-a44500d99727 ---> System.MemberAccessException: Cannot create an abstract class.
   at System.Runtime.Serialization.FormatterServices.nativeGetUninitializedObject(RuntimeType type)
   at NServiceBus.MessageInterfaces.MessageMapper.Reflection.MessageMapper.CreateInstance(Type t) in c:\BuildAgent\work\1b05a2fea6e4cd32\src\NServiceBus.Core\MessageInterfaces\MessageMapper\Reflection\MessageMapper.cs:line 426

This even happens if we instead of an ExpressionNode require a LambaExpressionNode (which is the underlying type generated by .ToExpressionNode();

Any ideas at all? Should I be bugging the guys @ NServiceBus instead since there is a fault on their end?

FYI what we want to accomplish is a 'RefinedQuery' Object with a Take, Skip, Where and OrderBy property. In order to allow the clients to filter their screens. The Take and Skip will simply be integer values, the OrderBy I've yet to wrap my head around and the Where property I'd like to use the ExpressionNode to allow for nice hardcoded filtering on the client side.

**Comment by Odeanathus** [comment]
Spend some more time looking and poking and I think it has too do with NServiceBus using it's own serializer; http://docs.particular.net/nservicebus/performance

Which seems to not be able serialize/deserialize this properly :-(

Think I need to slap them around or fix this myself with some work arounds.

**Comment by esskar** [comment]
Fun to see that Serialize.Linq is used in various projects!

**Comment by Odeanathus** [comment]
Yes well, it's pretty lightweight and to the point. It does not add bells and whistles and allows us to do further implementation, since currently I don't want to add a WCF service or do anything like OData.

FYI, Currently I'm writting a wrapper class that will simply serialize/deserialze to string on both ends. It's not super clean or neat but it'll work I think.

**Comment by esskar** [comment]
can you configure the serialization? If they use Json.NET for example, you could set `TypeNameHandling = TypeNameHandling.Objects`, and solve the problem

**Comment by Odeanathus** [comment]
I can, but then I'd need to implement a different serializer for the whole servicebus which I do not want (their serializer is actually really fast).

I've solved it differently, same with the orderby by simply serializing those manually to string and then manually deserializing.

It's a pretty neat little solution this way I feel.
