### ISSUE TITLE
SerializationContext lacking

### ISSUE THREAD

**Issue by Odeanathus** [esskar/Serialize.Linq#46]
Not sure if this would count as an issue or maybe it's more of a feature request or the likes (I'm no github guru so I might be doing something wrong here).

But basically what we're doing (as you might have guesed from my previous 'issue') is serializing an expression and then we're sending this string through NServiceBus and deserializing it. What I'm lacking at the moment is a ExpressionContext to be able to translate from a Dto Expression to an expression on our actual class.

If I dive into your code though I see;

public Expression DeserializeText(string text)
        {
            var node = this.TextSerializer.Deserialize<ExpressionNode>(text);
            return node == null ? null : node.ToExpression();
        }

Surely adding an overload which does;

public Expression DeserializeText(string text, ExpressionContext expressionContext)
        {
            var node = this.TextSerializer.Deserialize<ExpressionNode>(text);
            return node == null ? null : node.ToExpression(expressionContext);
        }

Should allow for me to simply state the expressioncontext right on the deserialization and would keep me from needing to cast the expression back to a ExpressionNode and then adding the context to turn it back into an expression.

Maybe i'm missing some super easy way of doing this though, it's entirely possible.

**Comment by Odeanathus** [comment]
Actually, the way I'm solving it now isn't all that bad, I simply use the JsonSerializer Deserialize<ExpressionNode>() method to serialize it as an ExpressionNode and then I call .ToExpression with the actual context. It's more work then needed (and I still need to test it) but it's not as bad as calling .ToExpressioNode().ToExpression(ExpressionContext);

**Comment by vsoldatkin** [comment]
I think it worth a try and may actually be considered as an improvement proposal related to #44

**Comment by esskar** [comment]
is adding ExpressionContext enough? or am I missing something?

**Comment by Odeanathus** [comment]
You are not missing anything, just adding that overload is enough. It's nothing major (as I manage to work around it in a nice way due to just beeing able to use the JsonSerializer) but it's a minor change that could add some confinience for others (and myself :-D)

**Comment by esskar** [comment]
glad, it is so simple ;)
