### ISSUE TITLE
Assembly Version .NET45

### ISSUE THREAD

**Issue by MichelZ** [esskar/Serialize.Linq#48]
Hi

In the NuGet Package, the assembly version for the .NET4.5 package is 1.2.2.0 instead of 1.2.3.0...
Could you correct that?

Thanks
Michel

**Comment by AmitGee** [comment]
Ditto - assembly versions should be the same between net40 and net45 since it causes issues when used with solutions containing a mix of projects targeting different versions

**Comment by esskar** [comment]
fixed with nuget version 1.2.4
