### ISSUE TITLE
Inheritance Deserialization

### ISSUE THREAD

**Issue by Odeanathus** [esskar/Serialize.Linq#49]
Three objects, base class named, Debtor (abstract which has a few properties one being Id), IndividualDebtor & CompanyDebtor which inherit from the Debtor class.

I can serialize and deserialize the object(s) just fine untill I start filtering based on a property from the base class, in my case Id.

I get the following exception;

An exception of type 'System.ArgumentException' occurred in System.Core.dll but was not handled in user code

Additional information: Property 'Int32 Id' is not defined for type 'Cms.Entities.Models.IndividualDebtor'

Which made me confused since why would a property have the name 'Int32 Id', So I looked at the json string which was produced (in the interest of completion I also added the expression for the a property which is defined on the IndividualDebtor class, both strings look very similar for me, including the 'signature' which starts with the type in both cases.

```
{"__type":"LambdaExpressionNode:#Serialize.Linq.Nodes","NodeType":18,"Type":{"GenericArguments":[{"Name":"Cms.Messages.Dto.IndividualDebtor"},{"Name":"System.Boolean"}],"Name":"System.Func`2"},"Body":{"__type":"MemberExpressionNode:#Serialize.Linq.Nodes","NodeType":23,"Type":{"Name":"System.Boolean"},"Expression":{"__type":"MemberExpressionNode:#Serialize.Linq.Nodes","NodeType":23,"Type":{"GenericArguments":[{"Name":"System.DateTime"}],"Name":"System.Nullable`1"},"Expression":{"__type":"ParameterExpressionNode:#Serialize.Linq.Nodes","NodeType":38,"Type":{"Name":"Cms.Messages.Dto.IndividualDebtor"},"Name":"d"},"Member":{"DeclaringType":{"Name":"Cms.Messages.Dto.IndividualDebtor"},"Signature":"System.Nullable`1[System.DateTime] DateOfBirth"}},"Member":{"DeclaringType":{"GenericArguments":[{"Name":"System.DateTime"}],"Name":"System.Nullable`1"},"Signature":"Boolean HasValue"}},"Parameters":[{"__type":"ParameterExpressionNode:#Serialize.Linq.Nodes","NodeType":38,"Type":{"Name":"Cms.Messages.Dto.IndividualDebtor"},"Name":"d"}]}
```
```
{"__type":"LambdaExpressionNode:#Serialize.Linq.Nodes","NodeType":18,"Type":{"GenericArguments":[{"Name":"Cms.Messages.Dto.IndividualDebtor"},{"Name":"System.Boolean"}],"Name":"System.Func`2"},"Body":{"__type":"BinaryExpressionNode:#Serialize.Linq.Nodes","NodeType":13,"Type":{"Name":"System.Boolean"},"Left":{"__type":"MemberExpressionNode:#Serialize.Linq.Nodes","NodeType":23,"Type":{"Name":"System.Int32"},"Expression":{"__type":"ParameterExpressionNode:#Serialize.Linq.Nodes","NodeType":38,"Type":{"Name":"Cms.Messages.Dto.IndividualDebtor"},"Name":"d"},"Member":{"DeclaringType":{"Name":"Cms.Messages.Dto.Debtor"},"Signature":"Int32 Id"}},"Method":{},"Right":{"__type":"ConstantExpressionNode:#Serialize.Linq.Nodes","NodeType":9,"Type":{"Name":"System.Int32"},"Value":2}},"Parameters":[{"__type":"ParameterExpressionNode:#Serialize.Linq.Nodes","NodeType":38,"Type":{"Name":"Cms.Messages.Dto.IndividualDebtor"},"Name":"d"}]}
```

Maybe I'm doing something horribly wrong since It seems odd to me that i'd be the first to try this with some form of inheritance. If any more information (like code snippets) are required I'd be more than happy to add those.

**Comment by esskar** [comment]
can you provide a unit test that fails?

**Comment by Odeanathus** [comment]
I'll try and whip one together tomorrow, any prefered way of getting it? (Should I just zip it all and upload it somewhere or would you like a 'wall of text' here :-) Assuming I can get it to fail in a small unit test. (It's failing in my system integration tests atm).

**Comment by Odeanathus** [comment]
I've found the problem, which isn't actually in Serialize.Linq but in an example we use that you posted on your blog in the past, since your blog seems down here is the web archive link;

http://web.archive.org/web/20130430051839/http://blog.esskar.de/articles/2013/1/serialize_linq_dto_and_business.html

You mention the following snippet which we used to great success in the past (before we had a class that inherited;

''''class MyExpressionContext : ExpressionContext
    {
        public override Type ResolveType(TypeNode node)
        {
            var type = base.ResolveType(node);
            if(type == null)
                return null;
                        
            if(type == typeof(PersonDto))
                return typeof(Person);
            return type;
        }
    }
'''
We altered it slightly to be generic and what not but I got things to work when I actually checked on inheritance see the following snippet;

'''
public override Type ResolveType(TypeNode node)
        {
            var type = base.ResolveType(node);
            if (type == null)
                return null;

            Type dtoType = typeof (TDto);

            if (type == dtoType || dtoType.IsSubclassOf(type))
                return typeof(TActual);
            return type;
        }
'''

Since this isn't an issue within Serialize.Linq at all i'll close this, however should you decide to blog again (or maybe this code is in the examples as well, I didn't check that) you could change it slightly to allow for the inheritance.
