### ISSUE TITLE
serialization issues

### ISSUE THREAD

**Issue by squarewave24** [esskar/Serialize.Linq#50]
This is a great utility and i'd love to make it work for me. 

My first test was this simple predicate 

````js
  var arr = new string[] {"one","two"}; // initially this was a List<string> but couldn't make it work with serializer
  var results = new myObj<MyType>().Where(x => arr.Contains(x.Code) && x.Date >= dateFrom);
````
if arr is List<string> I was getting a ton of issues complaining about serialization of List<string> and ArrayOfString. 

I noticed that I can do this 

````js
  var bs = new BinarySerializer();
  bs.AddKnownType(typeof(string[]));
````

whenever I tried adding List<string> as a known type it would always complain that it either exists, or there was a conflict with List + Array being added together. So the only way I could make it work was registering known type string[] and using only this in my predicate. 

the outcome however looks like this 

````js 
x => (value(System.String[]).Contains(x.Code) AndAlso ...
````

as you see it only calls ToString on the Array, and contents are not shown.

**Comment by esskar** [comment]
Before I explain, i have a question: what is your expected output after deserialization?

**Comment by squarewave24** [comment]
hey thanks for quick reply

2 use cases i can think of that would be useful for me:

1. ability to serialize a predicate over WCF to be deserialized on the server for actual EF query
2. log what is being sent 

in both cases the contents of the array are important. perhaps there is another way to do a "Where X in" predicate that makes more sense?

**Comment by esskar** [comment]
Hi, contains are not shown, but the values are there.
if you navigate into the expression three, you will see that the values are actually bound.
i added some tests to proove it.

With Json:
https://github.com/esskar/Serialize.Linq/commit/05c8dfcf933e3b623f0f50b796df35699c330e21#diff-1f764cf1b5a7c3bb188739b8b49650b6R68

With Binary:
https://github.com/esskar/Serialize.Linq/commit/05c8dfcf933e3b623f0f50b796df35699c330e21#diff-1f764cf1b5a7c3bb188739b8b49650b6R86

For the Array vs List serialization problem:
It seems that you can either have `T[]` or `List<T>` as known types, but not both,
Previous version out added `T[]`, now there are two parameters

`AutoAddKnownTypesAsArrayTypes`: default true, `T[]` will be added
`AutoAddKnownTypesAsListTypes`: default false, `List<T>`will be added

only one of these parameters can be true at any given time.
Look here for an example and test:
https://github.com/esskar/Serialize.Linq/commit/05c8dfcf933e3b623f0f50b796df35699c330e21#diff-1f764cf1b5a7c3bb188739b8b49650b6R38

I will merge it to master branch soon!

**Comment by squarewave24** [comment]
hey thanks for explaining and the examples! 

these look great
