### ISSUE TITLE
link to blog is broken in README.md

### ISSUE THREAD

**Issue by fir3pho3nixx** [esskar/Serialize.Linq#52]
Hi, Tried clicking on it and it did not load. Would have liked to read your article :)

**Comment by epsitec** [comment]
The blog http://blog.esskar.de is no longer online. What is the issue there? Do you need some support?

**Comment by MeirionHughes** [comment]
It would be nice to have a basic example of usage; I presume the blog; cache of blog is here: https://web.archive.org/web/20130220065551/http://blog.esskar.de/

**Comment by esskar** [comment]
@MeirionHughes there is an example project

**Comment by fir3pho3nixx** [comment]
Closing.
