### ISSUE TITLE
Collection serialization expression 'contains' 

### ISSUE THREAD

**Issue by mc-ren** [esskar/Serialize.Linq#56]
So unless I am doing something wrong, this looks like it's the same issue assafw is seeing (#53 below). I have the following:

```C#
            var enterpriseKeys = new List<long?> { 1, 2, 3, 4 };

            var predicatePart =
                (Expression<Func<GroupEntity, bool>>)
                (groupType =>
                 enterpriseKeys.Contains(groupType.GroupEnterpriseKey));

            var serializeTo = new ExpressionSerializer(new XmlSerializer());
            var predicatePartSerializedToString = serializeTo.SerializeText(predicatePart);
````

I get the error as follows:

`
Error converting type: Type 'System.Collections.Generic.List`1[[System.Nullable`1[[System.Int64, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]' with data contract name 'ArrayOfNullableOflong:http://schemas.datacontract.org/2004/07/System' is not expected. 
`

`Consider using a DataContractResolver or add any types not known statically to the list of known types - for example, by using the KnownTypeAttribute attribute or by adding them to the list of known types passed to DataContractSerializer.
`

**Comment by esskar** [comment]
Thanks for that. I fixed it. See Unit Test for your Issue: https://github.com/esskar/Serialize.Linq/blob/master/src/Serialize.Linq.Tests/Issues/Issue56.cs
