### ISSUE TITLE
incorrect serialization of TypeBinaryExpression node

### ISSUE THREAD

**Issue by gulbanana** [esskar/Serialize.Linq#61]
Hi, I'm using Serialize.Linq on some weird expression trees and I've found a bug. This tree:
`{null.Where(entity => ((entity TypeEqual Farm) AndAlso Convert(entity.Animals).Any()}	`
deserializes as this non-equivalent tree:
`{null.Where(entity => ((entity Is Farm) AndAlso Convert(entity.Animals).Any()}`

The TypeEqual has become an Is, representing an assignability check instead of an equality check. I believe the issue is in https://github.com/esskar/Serialize.Linq/blob/master/src/Serialize.Linq/Nodes/TypeBinaryExpressionNode.cs - it does not check the NodeType, and unconditionally deserialises to Expression.TypeIs.

Here's a pull request which hopefully contains the fix: https://github.com/esskar/Serialize.Linq/pull/60

**Comment by esskar** [comment]
thanks for that. was not aware of it. merged it.
