### ISSUE TITLE
no strong name in net 4.5 version 

### ISSUE THREAD

**Issue by kinstya** [esskar/Serialize.Linq#66]
Hi, looks like a 4.5 version is not signed.
Is it intentional?

**Comment by sgavriel** [comment]
I have the same problem :-(

**Comment by kinstya** [comment]
Just did it on my self and it worked

**Comment by sgavriel** [comment]
Yep, did that also. I used this:
https://brutaldev.com/post/NET-Assembly-Strong-Name-Signer

**Comment by esskar** [comment]
fixed
