### ISSUE TITLE
Serialize from Expression to String. Using instances value in the predicate.

### ISSUE THREAD

**Issue by marcelmunarolo** [esskar/Serialize.Linq#68]
Dear Colleague,

Please, see this example:

    class MyEntity
    {
        public string Name { get; set; }
    }
...
            Expression<Func<MyEntity, bool>> where = x => x.Name == "Peter";
            var exp = where.ToExpressionNode().ToString();
            Console.WriteLine(exp);
...

The output is perfect, like this: "x => (x.Name == "Peter")"
However, if we change a little bit, the result is different, see:

...
            var obj = new MyEntity {Name = "Peter"};
            Expression<Func<MyEntity, bool>> where = x => x.Name == obj.Name;
            var exp = where.ToExpressionNode().ToString();
            Console.WriteLine(exp);
...

And the output is: "x => (x.Name == value(ConsoleApplication1.MyEntity).Name)"
Any chances here to get the same result as the first example?

Thanks in advance for your support.
Marcel

**Comment by esskar** [comment]
Hey,

try it like this

    var settings = new FactorySettings
    {
        AllowPrivateFieldAccess = true
    };
    var serializer = new ExpressionSerializer(new JsonSerializer());
    var exp= serializer.SerializeText(where, settings);

**Comment by marcelmunarolo** [comment]
Hey,

I tried your suggestion, and I received a SerializationException.
Message:
...
Consider using DataContractResolver or add some types not known statically to the list of known types - for example,
using KnownTypeAttribute attribute or by adding them to the list of known types passed to DataContractSerializer
...

Just for investigation, I added the Attribute in the Entity, like this:
[KnownType(typeof(MyEntity))]

And got this as serialization result:
...
{"__type":"L:#Serialize.Linq.Nodes","NT":18,"T":{"G":[
{"N":"ConsoleApplication1.MyEntity"},{"N":"System.Boolean"}],"N":"System.Func`2"},
"B":{"__type":"B:#Serialize.Linq.Nodes","NT":13,"T":{"N":"System.Boolean"},
"L":{"__type":"M:#Serialize.Linq.Nodes","NT":23,"T":{"N":"System.String"},
"E":{"__type":"P:#Serialize.Linq.Nodes","NT":38,"T":{"N":"ConsoleApplication1.MyEntity"},"N":"x"},
"M":{"D":{"N":"ConsoleApplication1.MyEntity"},"S":"System.String Name"}},
"M":{"D":{"N":"System.String"},"S":"Boolean op_Equality(System.String, System.String)"},
"R":{"__type":"M:#Serialize.Linq.Nodes","NT":23,"T":{"N":"System.String"},
"E":{"__type":"C:#Serialize.Linq.Nodes","NT":9,"T":{"N":"ConsoleApplication1.MyEntity"},
"V":{"__type":"MyEntity:#ConsoleApplication1","Name":"Peter"}},
"M":{"D":{"N":"ConsoleApplication1.MyEntity"},"S":"System.String Name"}}},
"P":[{"__type":"P:#Serialize.Linq.Nodes","NT":38,"T":{"N":"ConsoleApplication1.MyEntity"},"N":"x"}]}
...

However this serialization is too big, and I cannot use this on my problem, which is create cache keys. The serialized expression should be as short as possible and explicitly show the values used in the conditionals.

I will appreciate any ideas on how to get it done.
Cheers,
Marcel

**Comment by esskar** [comment]
ok. i will fix it.

**Comment by esskar** [comment]
fixed. thanks for reporting! (y)

**Comment by marcelmunarolo** [comment]
It works like a charm now!   :)
Many thanks!
I am looking forward the new nuget package!
