### ISSUE TITLE
Support for .net core and new project structure in VS2015

### ISSUE THREAD

**Issue by StefH** [esskar/Serialize.Linq#72]
Hi @esskar ; this library gives a perfect opportunity to convert to the new VS2015 (dnx/.net) core structure, so that you can have 1 project which just outputs .net 40, .net 45, sl and dnxcore50.

I'm willing to start on this, however do you have time (and do you want) to merge my forked project changes back to your project ?

Or should I just create a copy and totally fork away ?

See also my comment at : https://github.com/davidfowl/DynamicLinq/issues/5

**Comment by esskar** [comment]
Hey @StefH planed to do that soon.
Thanks and Cheers.

**Comment by StefH** [comment]
See https://github.com/esskar/Serialize.Linq/pull/73

**Comment by StefH** [comment]
Any update on this ?

Note that this pull-request is still based on dnx core, it needs some updates since the dotnet rc2 is out.

**Comment by esskar** [comment]
.netcore1.1 is now supported
