### ISSUE TITLE
No support for derived interfaces

### ISSUE THREAD

**Issue by yhurynovich** [esskar/Serialize.Linq#74]
Let's assume you are building expression against an interface Interface2 where Interface2:Interface1

ToBooleanExpression method will fail when attempting to reflect Interface1 interface properties.

NEED TO FLATTEN properties for reflection

**Comment by esskar** [comment]
@yhurynovich Thanks. Can you build an unit test for that?

**Comment by esskar** [comment]
i close this. if you can give me an example/unit-test, feel free to open it again
