### ISSUE TITLE
ToExpressionNode serializing whole class

### ISSUE THREAD

**Issue by EpsilonRepo** [esskar/Serialize.Linq#76]
Hi,

I'm passing an ExpressionNode object to my WCF service to make EF queries on the backend.
Everything works fine as long as I use constants or variables that are in the same scope.

example (GetSingleEntity calls ToExpressionNode() and passes the result to the service):
```
int value2 = 0;
GetSingleEntity<T>(s => s.prop1 == "value1" && s.prop2 == value2);
```

When the value2 variable is a foreach loop variable for instance, the ToExpressionNode() seems to serialize the whole class that contains the method. and sometimes breaks because that class is not serializable.

One workaround is to declare variables with the same values before de GetSingleEntity call, and use those, but that cannot be the solution.

Can you help me on this?

Best Regards,
Alain

**Comment by esskar** [comment]
can you build a unit test for that?

**Comment by esskar** [comment]
i will close this issue as i need a unit test for this. reopen if you can provide one. thanks.
