### ISSUE TITLE
WCF Service Deserialize parameter failed

### ISSUE THREAD

**Issue by cSteusloff** [esskar/Serialize.Linq#77]
I use a WCF Service and serialize my request with your library. The response from service call the following error Message in Reference.cs:
> Type '{0}' cannot be added to list of known types since another type '{1}' with the same data contract name '{2}:{3}' is already present. If there are different collections of a particular type - for example, List and Test[], they cannot both be added as known types. Consider specifying only one of these types for addition to the known types list.

Complete german error message:
> Der Typ "**WCFServices.MemberInfoNodeList**" kann der Liste bekannter Typen nicht hinzugefügt werden, da bereits ein anderer Typ "Serialize.Linq.Nodes.MemberInfoNodeList" mit demselben Datenvertragsnamen "http://schemas.datacontract.org/2004/07/Serialize.Linq.Nodes:MemberInfoNodeList" vorhanden ist. Wenn verschiedene Auflistungen eines bestimmten Typs vorhanden sind, z. B. List<Test> und Test[], können nicht beide als bekannte Typen hinzugefügt werden. Fügen Sie ggf. nur einen dieser Typen der Liste der bekannten Typen hinzu.

I have no idea to fix this issue. Is there a problem with **KnownType(typeof(MemberInfoNodeList))** in https://github.com/esskar/Serialize.Linq/blob/master/src/Serialize.Linq/Nodes/Node.cs ?

The stack trace:
`
System.Runtime.Serialization.DataContract.CheckAndAdd(Type type, Dictionary`2 typesChecked, Dictionary`2& nameToDataContractTable)
System.Runtime.Serialization.DataContract.ImportKnownTypeAttributes(Type type, Dictionary`2 typesChecked, Dictionary`2& knownDataContracts)
System.Runtime.Serialization.DataContract.CheckAndAdd(Type type, Dictionary`2 typesChecked, Dictionary`2& nameToDataContractTable)
System.Runtime.Serialization.DataContract.ImportKnownTypeAttributes(Type type, Dictionary`2 typesChecked, Dictionary`2& knownDataContracts)
System.Runtime.Serialization.DataContract.CheckAndAdd(Type type, Dictionary`2 typesChecked, Dictionary`2& nameToDataContractTable)
System.Runtime.Serialization.DataContract.ImportKnownTypeAttributes(Type type, Dictionary`2 typesChecked, Dictionary`2& knownDataContracts)
System.Runtime.Serialization.DataContract.CheckAndAdd(Type type, Dictionary`2 typesChecked, Dictionary`2& nameToDataContractTable)
System.Runtime.Serialization.DataContract.ImportKnownTypeAttributes(Type type, Dictionary`2 typesChecked, Dictionary`2& knownDataContracts)
System.Runtime.Serialization.DataContract.CheckAndAdd(Type type, Dictionary`2 typesChecked, Dictionary`2& nameToDataContractTable)
System.Runtime.Serialization.DataContract.ImportKnownTypeAttributes(Type type, Dictionary`2 typesChecked, Dictionary`2& knownDataContracts)
System.Runtime.Serialization.DataContract.ImportKnownTypeAttributes(Type type)
System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper.get_KnownDataContracts()
System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
System.Runtime.Serialization.DataContractSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
System.Runtime.Serialization.DataContractSerializer.ReadObject(XmlDictionaryReader reader, Boolean verifyObjectName)
System.ServiceModel.Dispatcher.DataContractSerializerOperationFormatter.PartInfo.ReadObject(XmlDictionaryReader reader, XmlObjectSerializer serializer)
System.ServiceModel.Dispatcher.DataContractSerializerOperationFormatter.DeserializeParameterPart(XmlDictionaryReader reader, PartInfo part, Boolean isRequest)
`

Thanks

**Comment by esskar** [comment]
hi. you generate the client using a service reference, right? The generation is wrong. I do not know why, but you basically need to edit it by hand.
