### ISSUE TITLE
ConstantExpressionNode deserialization error

### ISSUE THREAD

**Issue by artemkuzmyk** [esskar/Serialize.Linq#83]
If I use some lambda with constant type != string after deserialization  ConstantExpressionNode  will have string type by default and in this cases I have error : 'The binary operator Equal is not defined for the types 'System.Int32' and 'System.String'.'
You can reproduce it using some Enum equal operation.

```
Expression<Func<HttpWebResponse, bool>> predicate = be => be.StatusCode == HttpStatusCode.Accepted;
var node = predicate.ToExpressionNode();
var json = node.ToJson();
var jnode = json.FromJson<LambdaExpressionNode>();
var func = jnode.ToExpression<Func<HttpWebResponse, bool>>().Compile(); //EXCEPTION
```

**Comment by esskar** [comment]
thanks. i will look into it tonight.

**Comment by esskar** [comment]
@artemkuzmyk  where are the ToJson and FromJson  extensions are coming from?

**Comment by artemkuzmyk** [comment]
@esskar it's from ServiceStack.Text.4.5.8

**Comment by esskar** [comment]
@artemkuzmyk seems to be an issue with ServiceStack.Text then as

        [TestMethod]
        public void Test2()
        {
            Expression<Func<HttpWebResponse, bool>> predicate = be => be.StatusCode == HttpStatusCode.Accepted;
            var node = predicate.ToExpressionNode();
            
            var func = node.ToExpression<Func<HttpWebResponse, bool>>().Compile();
            Assert.IsNotNull(func);
        }

        [TestMethod]
        public void Test3()
        {
            var serializer = new ExpressionSerializer(new JsonSerializer());

            Expression<Func<HttpWebResponse, bool>> predicate = be => be.StatusCode == HttpStatusCode.Accepted;

            var json = serializer.SerializeText(predicate);
            var jnode = (Expression<Func<HttpWebResponse, bool>>)serializer.DeserializeText(json);
            var func = jnode.Compile();
            Assert.IsNotNull(func);
        }

work just fine

**Comment by esskar** [comment]
but i will try to get to this....

**Comment by esskar** [comment]
not supported for now.
