### ISSUE TITLE
Package not working in .Net Core project

### ISSUE THREAD

**Issue by BmTestE60** [esskar/Serialize.Linq#84]
Nuget package installed correctly but classes, extensions, namespace not visible. I tried to download sources, build and reference to dll, it's not working too
This is my .net core csproj file
`<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
    <AssemblyName>MyAssemblyName</AssemblyName>
    <PackageId>MyPackageId</PackageId>
    <PackageTargetFallback>$(PackageTargetFallback);dotnet5.6;portable-net45+win8</PackageTargetFallback>
    <RuntimeFrameworkVersion>1.1.2</RuntimeFrameworkVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.ValueTuple" Version="4.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="." />
    <ProjectReference Include="." />
  </ItemGroup>

</Project>
`

**Comment by esskar** [comment]
thanks. i will check that asap

**Comment by esskar** [comment]
hey. i had no problem with the library itself. installed using nuget. it compiled as expected. there was a runtime problem, some dependencies were missing. fixed that and published a new version

**Comment by esskar** [comment]
![image](https://user-images.githubusercontent.com/65206/30910589-78a0b81e-a3c4-11e7-935c-3c85857ee957.png)

**Comment by esskar** [comment]
finally had time to push version 1.5.0
is this still an issue?

**Comment by StefH** [comment]
Possible also my PR solves this issue:
https://github.com/esskar/Serialize.Linq/pull/94

**Comment by esskar** [comment]
I just published version 1.7.0 that supports .net standard 1.3 and 2.0
does this help for you?
