### ISSUE TITLE
Universal apps support

### ISSUE THREAD

**Issue by alex4998** [esskar/Serialize.Linq#86]
I tried to install the nuget package for my universal app 14393 but it failed. Any plans to support universal platform?

Thank you

**Comment by esskar** [comment]
what was the error?

**Comment by esskar** [comment]
it is not so simple. give me time til the weekend

**Comment by alex4998** [comment]
Thank you for the prompt response. Let me know if I can help you with anything in this regard. Just to recap the conditions I'm trying to install the NuGet in. I have a universal app targeting platform version 14393. The project was created as "Blank App (Universal Windows) C#." I use VS2017. In the application I have a reference to Microsoft.NETCore.UniversalWindowsPlatform v5.3.3 (not the latest one but I can change it if necessary).
The error is this
Package Serialize.Linq 1.3.2.1 is not compatible with uap10.0.14393 (UAP,Version=v10.0.14393) / win10-x64. Package Serialize.Linq 1.3.2.1 supports:
  - net40 (.NETFramework,Version=v4.0)
  - net45 (.NETFramework,Version=v4.5)
  - netcoreapp1.1 (.NETCoreApp,Version=v1.1)
  - sl5 (Silverlight,Version=v5.0)
  - wp8 (WindowsPhone,Version=v8.0)
  - wp8-arm (WindowsPhone,Version=v8.0,Profile=arm)
Package restore failed. Rolling back package changes for 'Update.Universal'.

**Comment by esskar** [comment]
Problem is the simulation of AppDomain functionality

**Comment by esskar** [comment]
looks good so far. i think i will publish next week

**Comment by alex4998** [comment]
Hm... Interesting. You mentioned AppDomain. I know AppDomain concept does not exist in UWP. I'm glad you found a way to overcome this shortage. I didn't quite understand your comment about signing. If you are asking if we sign the assemblies then the answer is no. Is it required? Looking forward to the new version on NuGet to try. Thank you.

**Comment by esskar** [comment]
no prob.
the "added a commit that referenced" comments are just me adding code regarding your issue.

**Comment by esskar** [comment]
version 1.4.0 is published. i was not sure about the nuget folder structur. please try it.

**Comment by alex4998** [comment]
Thank you. It compiles and simple scenarios work something like this

`            Expression<Predicate<int>> expressionIn = v => v > 10;
            ExpressionNode expressionNode = expressionIn.ToExpressionNode();

            Expression<Predicate<int>> expressionOut = expressionNode.ToExpression<Predicate<int>>();
            Predicate<int> predicate = expressionOut.Compile();

            bool res = predicate(8);`

   I tried a more advanced scenario and that didn't work in UWP but it worked fine in Desktop app (.NET 4.5). Here is the test project - https://1drv.ms/u/s!An2zN5dKMyaUhNcg6EQ0L2RlIZB9bA, could you take a look?
   If I try to debug it I get this error and everything crash
![image](https://user-images.githubusercontent.com/15015347/31680012-961dd61e-b338-11e7-8673-4feea78a50d4.png)
   If I run the test without debugging it hangs up.

**Comment by alex4998** [comment]
Did you have a chance to look at this issue? Do you plan to do it any soon?

**Comment by esskar** [comment]
can you add the sample code here, i cannot access your link.thanks

**Comment by alex4998** [comment]
I don't see a way to attach a file directly to a message. I double checked the link https://1drv.ms/u/s!An2zN5dKMyaUhNcg6EQ0L2RlIZB9bA should work. You should be able to download a zip file with the test project. If you can't what error it displays?

**Comment by esskar** [comment]
it was actually a bug when showing the expression node in the debug

**Comment by esskar** [comment]
will release a new version soon

**Comment by alex4998** [comment]
It looks like it is not updated yet. Any progress in fixing the issue?

**Comment by alex4998** [comment]
Anything?

**Comment by alex4998** [comment]
It would be nice to hear something back. Thank you.

**Comment by esskar** [comment]
will try to push it tomorrow

**Comment by esskar** [comment]
finally had time to push version 1.5.0
