### ISSUE TITLE
Support for .NET Standard

### ISSUE THREAD

**Issue by aloisdeniel** [esskar/Serialize.Linq#90]
Great work, thanks!

Having support for .NET Standard projects would be great!

As a side note, I wouldn't store binaries (`.nupkg`) into the sources.

**Comment by StefH** [comment]
The best would be to restructure the whole source code to define only 1 project which supports all the frameworks from net 4.0 up to netstandard 1.1

I can make a PR for that.

**Comment by esskar** [comment]
@StefH that would be great.

**Comment by StefH** [comment]
Support for NETStandard 1.x is difficult due to `ExpressionContext` -> `AppDomain.CurrentDomain.GetAssemblies()`

This code should actually not be in this library, but should be provided by the calling application.

I'll have a look on how to solve this.

**Comment by StefH** [comment]
See https://github.com/esskar/Serialize.Linq/pull/94

**Comment by esskar** [comment]
I just published version 1.7.0 that supports .net standard 1.3 and 2.0
thanks @StefH for your support. had some private issues to sort out. thanks for your patience.
