### ISSUE TITLE
Support :- [MS-LETSF]: LINQ Expression Tree Serialization Format

### ISSUE THREAD

**Issue by SPEMoorthy** [esskar/Serialize.Linq#99]
Hi
Is this library supporting [MS-LETSF]: LINQ Expression Tree Serialization Format ?
Ref :- https://msdn.microsoft.com/en-us/library/jj131805(v=sql.105).aspx

**Comment by esskar** [comment]
currently on vacation, i will look into this.

**Comment by esskar** [comment]
why is mircosoft still doing xml?
i will check my schedule and try to add it into one of the next releases.

**Comment by esskar** [comment]
@SPEMoorthy is this a real requirement you need to support or is it just nice to have?

**Comment by SPEMoorthy** [comment]
This is a nice to have requirement for our project
